Add setup_gnome_display_manager playbook
brett060102/ansible-container pull request #32
Opened 2023-09-05 16:51 UTC by HVSharma12

Add setup_gnome_display_manager playbook

2023-09-06 07:33 UTC, pdostal requested changes
I feel that installing packages via Ansible on transactional system from that system itself is a bit nonsense as the system should be 'production' and the Ansible should be run from a client.

The Ansible can then reboot that target system and continue after that just fine.

2023-09-06 07:33 UTC, pdostal commented on examples/ansible/setup_gnome_display_manager.yml
> +        - python3-selinux
Again, this is static. Why is it defined as variable?

2023-09-06 07:33 UTC, pdostal commented on examples/ansible/setup_gnome_display_manager.yml
> +        - ((workload.required_pkgs | default([])) | length) > 0
What doesthis even mean?

2023-09-06 07:33 UTC, pdostal commented on examples/ansible/setup_gnome_display_manager.yml
> +        state: present
```suggestion
      ansible.builtin.package:
        name: ['accountsservice', 'systemd-experimental', 'python3-selinux']
        state: present
```

2023-09-06 07:33 UTC, pdostal commented on examples/ansible/setup_gnome_display_manager.yml
> +      register: required_pkgs_install
```suggestion
      notify: reboot
    - name: Reboot right now if necessary
      meta: flush_handlers
            
handlers:
  - name: reboot
    reboot:
      reboot_timeout: 600
      post_reboot_delay: 60
```

2023-09-06 07:33 UTC, pdostal commented on examples/ansible/setup_gnome_display_manager.yml
> +            msg: "Reboot required"
This is not needed.

2023-09-06 07:33 UTC, pdostal commented on examples/ansible/setup_gnome_display_manager.yml
> +        state: restarted
We just installed it. I suppose it only needs to be running?
```suggestion
        state: started
        enabled: true
```

2023-09-06 07:33 UTC, pdostal commented on examples/ansible/setup_gnome_display_manager.yml
> +        daemon_reload: true
just nit
```suggestion
        daemon_reload: true
      when: workload_runlabel_install.stdout.changed
```

2023-09-07 05:13 UTC, pdostal approved these changes
All good from my side. Just a question:

Before you merge such pull request, do you actually try to run the playbook somewhere?

2023-09-07 08:27 UTC, HVSharma12 commented
@pdostal Yes tested it on [ALP Dolomite 1.0 Milestone 3](https://susealp.io/downloads/alp-dolomite-1.0-milestone-3/)

2023-09-07 08:54 UTC, pdostal commented
Very cool :smile:

2023-09-07 13:15 UTC, brett060102 approved these changes
Looks great.

2023-09-08 07:42 UTC, merged